### ISSUE TITLE
Not works under Linux Mint 64bit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cclgroupltd/ccl-ssns#5]
```
What steps will reproduce the problem?
1. Linux Mint 16 Petra (64bit machine)
2. Download script & add exec rights to it
3. Run in command line:

    ./ccl_ssns.py ~/.config/google-chrome/Default/Current\ Tabs out.html

What is the expected output?

  Report generated, withot error.

What do you see instead?

Processing begins...
Error reading record begining at data offset 27.
Error caused by: unpack requires a bytes object of length 4.
Traceback follows for debugging:

---------------EXCEPTION BEGINS---------------
Traceback (most recent call last):
  File "./ccl_ssns.py", line 544, in load_iter
    command = read_command(f)
  File "./ccl_ssns.py", line 480, in read_command
    return read_tab_restore_command(command_buffer, command_id)
  File "./ccl_ssns.py", line 520, in read_tab_restore_command
    state = WebHistoryItem.from_bytes(state_blob[4:]) # first 32bits is the internal pickle size. We dont' need it.
  File "./ccl_ssns.py", line 225, in from_bytes
    return cls.from_stream(f)
  File "./ccl_ssns.py", line 276, in from_stream
    doc_state_count, = struct.unpack("<i", f.read(4))
struct.error: unpack requires a bytes object of length 4
----------------EXCEPTION ENDS----------------

NB: No further records will be read.
Processing finished.


What version of the product are you using? On what operating system?

   Current from trunk (master).  Linux Mint 16 Petra (64bit machine)

```

Original issue reported on code.google.com by `Ustimenk...@gmail.com` on 2 Apr 2014 at 7:55

**Comment by cclgroupltd** [comment]
Old version was acknowledged to be broken on newer versions of Chrome. New version should work with these files.
