### ISSUE TITLE
Should this project still work? Error reading record begining at data offset XX 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cclgroupltd/ccl-ssns#8]
```
$ chrome_tabs Current\ Tabs moo.html
Processing begins...
Error reading record begining at data offset 27.
Error caused by: unpack requires a bytes object of length 4.
Traceback follows for debugging:

---------------EXCEPTION BEGINS---------------
Traceback (most recent call last):
  File "/Users/david/bin/chrome_tabs", line 544, in load_iter
    command = read_command(f)
  File "/Users/david/bin/chrome_tabs", line 480, in read_command
    return read_tab_restore_command(command_buffer, command_id)
  File "/Users/david/bin/chrome_tabs", line 520, in read_tab_restore_command
    state = WebHistoryItem.from_bytes(state_blob[4:]) # first 32bits is the internal pickle size. We dont' need it.
  File "/Users/david/bin/chrome_tabs", line 225, in from_bytes
    return cls.from_stream(f)
  File "/Users/david/bin/chrome_tabs", line 276, in from_stream
    doc_state_count, = struct.unpack("<i", f.read(4))
struct.error: unpack requires a bytes object of length 4
----------------EXCEPTION ENDS----------------

NB: No further records will be read.
Processing finished.

$ chrome_tabs Last\ Session moo.html
Processing begins...
Error reading record begining at data offset 57.
Error caused by: unpack requires a bytes object of length 4.
Traceback follows for debugging:

---------------EXCEPTION BEGINS---------------
Traceback (most recent call last):
  File "/Users/david/bin/chrome_tabs", line 544, in load_iter
    command = read_command(f)
  File "/Users/david/bin/chrome_tabs", line 480, in read_command
    return read_tab_restore_command(command_buffer, command_id)
  File "/Users/david/bin/chrome_tabs", line 520, in read_tab_restore_command
    state = WebHistoryItem.from_bytes(state_blob[4:]) # first 32bits is the internal pickle size. We dont' need it.
  File "/Users/david/bin/chrome_tabs", line 225, in from_bytes
    return cls.from_stream(f)
  File "/Users/david/bin/chrome_tabs", line 276, in from_stream
    doc_state_count, = struct.unpack("<i", f.read(4))
struct.error: unpack requires a bytes object of length 4
----------------EXCEPTION ENDS----------------

NB: No further records will be read.
Processing finished.


What version of the product are you using? On what operating system?
OSX 10.9.5


Please provide any additional information below.

```

Original issue reported on code.google.com by `david.kr...@gmail.com` on 6 Feb 2015 at 4:38

**Comment by cclgroupltd** [comment]
Old version was acknowledged to be broken on newer versions of Chrome. New version should work with these files.
